#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process

# Get the pid of 4-to_infinity_and_beyond
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
