#!/usr/bin/env bash
# oops from 1 to 10 and:
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Best School" for the other iterations

while ((i < 10))
do
	if ((i == 3)); then
		echo "bad luck"
	elif ((i == 7)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
